image:
  name: leanprovercommunity/lean
  entrypoint: ["/bin/bash", "-c"]

build:
  cache:
    paths:
      - _target/
  script:
    - leanproject --version
    - leanproject get-mathlib-cache
    - leanproject build
